### ISSUE TITLE
When using CPython from Java, non-main threads started by Python can't attach()

### ISSUE THREAD

**Issue by KeithCaceres** [LeeKamentsky/python-javabridge#104]
I create a CPython instance inside Oracle Java 7 for the purpose of executing Python scripts in the JVM process. My Python script calls a module that starts its own Python thread. This module takes a Python object that is used as a callback handler (i.e. one of the object's instance methods gets invoked on this newly created Python thread).

When I attempt to call javabridge.attach() from this callback method (that is executed on the non-main Python thread), I get the following AssertionError exception:

```
Traceback (most recent call last):
  File "<string>", line 37, in __call__
  File "/usr/local/lib/python2.7/dist-packages/javabridge-1.0.14-py2.7-linux-x86_64.egg/javabridge/jutil.py", line 748, in attach
    _javabridge.jb_attach()
  File "_javabridge.pyx", line 397, in _javabridge.jb_attach (_javabridge.c:3154)
AssertionError
```

Callback code example:

```
class MessageHandler:
  def __init__(self):
    self.env_ = None
  
  def __call__(self, msg):
    global javabridge
    if self.env_ == None:
      self.env_ = javabridge.attach() # This throws exceptions.AssertionError
    # Process message here...
```

The assert that fails seems to be one checking whether __vm is None.  When this is run from Python I have no problem calling javabridge.start_vm() and then attaching from any thread. But when its started from a JVM process, __vm is None, calling javabridge.start_vm() fails (which I guess isn't surprising since it's already running inside a JVM), and there seems to be no way to get an env for any thread except the script's main thread.

Thanks,

Keith

**Comment by LeeKamentsky** [comment]
OK thanks again Keith. There was an oversight when I did the CPython code. It didn't set the global pointer to the JavaVM. It only needs that if you're creating an environment in a separate thread - in the calling thread, I was correctly storing the environment.

So now all good, please try it and see if it works. The CPython code hasn't been so heavily used so you are  a bit of a trailblazer here.

**Comment by KeithCaceres** [comment]
Hi Lee,

Yeah, I was looking at the CellProfiler source code to better understand how python-javabridge is used in the wild. I had a feeling I might be one of the few to invoke CPython from Java rather than Python.

I can confirm that your fix works. :-) Thanks again for the quick turn-around and for building this awesome library. Really nice work!

Thanks,

Keith
