### ISSUE TITLE
Can't find dependent libraries (Even though all the dependencies compile and Eclipse has the right paths)

### ISSUE THREAD

**Issue by dandavenport55** [LeeKamentsky/python-javabridge#109]
Your software for calling Python from Java is the only one that has what I need.  Everything built according to the documentation.  All the unit tests pass as well (provided running "python setup.py nosetests" runs the same tests as just calling "nosetests".  The latter fails).  I'm running under Windows, which is probably a mistake but it is what it is.  Trying the example of calling Java from Python worked great.  The example of calling Python from Java fails with 'Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Dan\workspace\javabridge-1.0.14\javabridge\jars\java2cpython.dll: Can't find dependent libraries.'  This is a Java error I think so I made sure Eclipse knew the path to the jar files.  I also added half a dozen paths in my path environment variable in case I missed some dll dependency.   Please give me a hint what to try.  :-)  I can supply all the stack traces and build information you'd like of course or anything else you need.  thx.  -Dan 

I also built it using both pip install and python

**Comment by dandavenport55** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Dan\workspace\javabridge-1.0.14\javabridge\jars\java2cpython.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at main.CPython.<clinit>(CPython.java:126)
	at main.MyClass.<clinit>(MyClass.java:10)
	at main.Main.<init>(Main.java:6)
	at main.Main.main(Main.java:11)

----------------------------------------------------------------------------------------------------

C:\Users\Dan\workspace\javabridge-1.0.14>python setup.py nosetests
running nosetests
running egg_info
writing dependency_links to javabridge.egg-info\dependency_links.txt
writing top-level names to javabridge.egg-info\top_level.txt
writing javabridge.egg-info\PKG-INFO
writing requirements to javabridge.egg-info\requires.txt
writing entry points to javabridge.egg-info\entry_points.txt
reading manifest file 'javabridge.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.pyx'
writing manifest file 'javabridge.egg-info\SOURCES.txt'
C:\Program Files\Java\jdk1.8.0_73\bin\javac.exe -source 6 -target 6 java\org\cellprofiler\runnablequeue\RunnableQueue.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
C:\Program Files\Java\jdk1.8.0_73\bin\javac.exe -source 6 -target 6 java\org\cellprofiler\javabridge\test\RealRect.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
C:\Program Files\Java\jdk1.8.0_73\bin\javac.exe -source 6 -target 6 java\org\cellprofiler\javabridge\CPython.java java\org\cellprofiler\javabridge\CPythonInvocationHandler.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: java\org\cellprofiler\javabridge\CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
copying build\lib.win-amd64-3.5\javabridge\_javabridge.cp35-win_amd64.pyd -> javabridge
error: could not delete 'javabridge\_javabridge.cp35-win_amd64.pyd': Access is denied

-------------------------------------------------------------------------------------------------

C:\Users\Dan\workspace\javabridge-1.0.14>nosetests
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
......................................Exception in thread "Thread-0" java.lang.NoSuchMethodError: copyValueOf
...................................Exception in thread "Thread-0" java.lang.NoSuchFieldError: NoSuchField
.Exception in thread "Thread-0" java.lang.NoClassDefFoundError: no/such/class
Caused by: java.lang.ClassNotFoundException: no.such.class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
..Exception in thread "Thread-0" java.lang.NoSuchFieldError: NoSuchField
.Exception in thread "Thread-0" java.lang.NoClassDefFoundError: no/such/class
Caused by: java.lang.ClassNotFoundException: no.such.class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
................................Exception in thread "Thread-0" java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
.........................Exception in thread "Thread-0" java.lang.NoSuchFieldError: NoSuchField
..Exception in thread "Thread-0" java.lang.NoSuchFieldError: NoSuchField
........................
----------------------------------------------------------------------
Ran 160 tests in 2.368s

OK

**Comment by dandavenport55** [comment]
si

**Comment by dandavenport55** [comment]
not great at this kind of thing.  Still open please.

**Comment by LeeKamentsky** [comment]
Hi Dave, a little short on time right now, but I will try to look at this in depth this week. Most of my development work on the Javabridge was done in Windows, so it should work, although the Java->Python direction has seen much less use than Python -> Java.

**Comment by LeeKamentsky** [comment]
The first thing I would try is to make sure that python27.dll is on your path. I am guessing that's the error. You might try running the "depends" tool (http://www.dependencywalker.com/) on java2cpython.dll to see what dlls are not being found.

**Comment by dandavenport55** [comment]
I'm using python 3.5 which my be the problem.  I'll check the name and path and let you know how it turns out.  Thx.


Sent from my Sprint Phone.-------- Original message --------From: LeeKamentsky <notifications@github.com> Date: 3/27/2017  11:37 AM  (GMT-05:00) To: LeeKamentsky/python-javabridge <python-javabridge@noreply.github.com> Cc: dandavenport55 <dandavenport55@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [LeeKamentsky/python-javabridge] Can't find dependent libraries
  (Even though all the dependencies compile and Eclipse has the right paths)
  (#109) 
The first thing I would try is to make sure that python27.dll is on your path. I am guessing that's the error. You might try running the "depends" tool (http://www.dependencywalker.com/) on java2cpython.dll to see what dlls are not being found.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LeeKamentsky/python-javabridge","title":"LeeKamentsky/python-javabridge","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LeeKamentsky/python-javabridge"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeeKamentsky in #109: The first thing I would try is to make sure that python27.dll is on your path. I am guessing that's the error. You might try running the \"depends\" tool (http://www.dependencywalker.com/) on java2cpython.dll to see what dlls are not being found."}],"action":{"name":"View Issue","url":"https://github.com/LeeKamentsky/python-javabridge/issues/109#issuecomment-289492097"}}}

**Comment by dandavenport55** [comment]
Found the problem.  Dependency walker is GREAT.  The problem is way down
deep inside of python 3.5.  I thought that might be the problem.
Otherwisek everything works.  Thanks for your help and dependency walker.
-Dan
