### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by KyonP** [LeeKamentsky/python-javabridge#124]
I've somehow managed to install java (cannot be installed 'apt-get' recently). and I stuck in here

```

# pip install javabridge 

Collecting javabridge
  Using cached javabridge-1.0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cEgnNT/javabridge/setup.py", line 393, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-build-cEgnNT/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/usr/lib/python2.7/posixpath.py", line 122, in dirname
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cEgnNT/javabridge/

```

I'm using JAVA 9.0.4, Ubuntu 14.04.

Anyone having this problem?

**Comment by LeeKamentsky** [comment]
Hi Kyon. At first glance, it looks like Javabridge is not finding the path to the Java libraries and similar. You might try to define the environment variable, "JAVA_HOME" to point to your version of Java. I just created an Anaconda environment with the JDK as a dependency and successfully installed Javabridge by setting JAVA_HOME to  $CONDA_PREFIX.

The following is my conda environment.yaml file:

```
name: jdk
channels:
- cyclus
dependencies:
- java-jdk
- python=2.7
- cython
- numpy
```
To create the Anaconda environment:
```
> conda env create -f environment.yaml
> source activate jdk
> export JAVA_HOME=$CONDA_PREFIX
> pip install javabridge
```
LMK if it worked for you. And for others, a recipe if you're on a box w/o Java and w/o root privileges.

**Comment by KyonP** [comment]
thanks, I'll try this one.
