### ISSUE TITLE
Can't import javabridge in Python in conda env, pythonw works

### ISSUE THREAD

**Issue by jni** [LeeKamentsky/python-javabridge#136]
I'm trying to build a minimal Python bundle, starting with a minimal conda environment, for a small application to analyse LIF files. I've got javabridge and python-bioformats working fine in my main Python 3.6, Anaconda environment. Unfortunately, this is a catch-all environment where everything lives and gets updated constantly, so I don't know *why* things work. The point is that when I `conda env create -f environment.yml` using the environment below, it *doesn't* work:

```yaml
name: podo
dependencies:
- python=3.6
- numpy
- scikit-image
- pip:
  - javabridge==1.0.15
  - python-bioformats
```

The version pin on javabridge is just my feeble attempt to replicate my main environment. 1.0.17 and master both fail in the same way:

```python
 $ python -c "import javabridge as jv"
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jni/projects/python-javabridge/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/jni/projects/python-javabridge/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/jni/projects/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/jni/projects/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jni/projects/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so
```

I don't really understand anything about "Frameworks", which is where the above error messages lead. Oddly enough everything works fine in IPython, and `pythonw -c "import javabridge as jv"` also works. But the latter is awkward when aiming to distribute an app. (Although maybe it isn't really?) Any advice is appreciated!

**Comment by LeeKamentsky** [comment]
I am no expert with OS/X and don't have access to an environment where I can recreate this. I am wondering if it works in IPython and doesn't in Python, which IPython and which Python is it using? Maybe one or the other is not the one from your Conda environment? Also, `/Users/jni/projects/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so` doesn't look like it's in a Conda environment - is that .so getting pulled from some place different than where it would be in ipython?

Things to try to diagnose might be:
```
which ipython
which python
```
and in IPython:
```
import javabridge as jv
print(jv.__file__)
```
to see if it's the same _javabridge...so that's being loaded in Python.

**Comment by jni** [comment]
Hi Lee, and thanks for getting back to me so quickly!

It's not actually an env thing — sorry about the confusion from my traceback. I just included the latest one, which was after running `pip install -e .` from the GitHub source into this environment. But the whole thing started with the env without specifying a version, then specifying version 1.0.15, then with conda install. (It appears they have a build on `defaults`.) e.g.

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jni/projects/podocytes/podocytes/lifio.py", line 6, in <module>
    import javabridge as jv
  File "/Users/jni/conda/envs/podo/lib/python3.6/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/jni/conda/envs/podo/lib/python3.6/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/jni/conda/envs/podo/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/jni/conda/envs/podo/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jni/conda/envs/podo/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so
```

Since my post I've found these two issues with various unhappy people that suggest no easy fix:

https://github.com/ContinuumIO/anaconda-issues/issues/199
https://github.com/conda-forge/python-feedstock/issues/23

I'm going to close this, as I believe the issue lies in conda, not here. I thought you might have run into this at some point e.g. while bundling CellProfiler. Thank you for the awesome package! =)

**Comment by LeeKamentsky** [comment]
Thanks for using it, Juan. Feel free to post here if there's something conda-related that needs to be done to make it all work.
