### ISSUE TITLE
Javabridge fails to be imported after increasing Java heap size

### ISSUE THREAD

**Issue by mbramerloh** [LeeKamentsky/python-javabridge#140]
After assigning a big RAM heap to be used by Java via 

`export _JAVA_OPTIONS=-Xmx128g`,

when importing javabridge in pyhton, I get the following error message:

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-27034589ebcc> in <module>()
----> 1 import javabridge

~/.local/lib/python3.5/site-packages/javabridge/__init__.py in <module>()
     23 if sys.platform.startswith('linux'):
     24     from .locate import find_jre_bin_jdk_so
---> 25     _, jdk_so = find_jre_bin_jdk_so()
     26     if jdk_so:
     27         import ctypes

~/.local/lib/python3.5/site-packages/javabridge/locate.py in find_jre_bin_jdk_so()
    204     """Finds the jre bin dir and the jdk shared library file"""
    205     jvm_dir = None
--> 206     java_home = find_javahome()
    207     if java_home is not None:
    208         found_jvm = False

~/.local/lib/python3.5/site-packages/javabridge/locate.py in find_javahome()
    119         elif re.match('^java', java_version_string) is not None:
    120             jdk_dir = os.path.join(java_dir, "..", "..")
--> 121         jdk_dir = os.path.abspath(jdk_dir)`
    122         return jdk_dir
    123     elif is_win:

UnboundLocalError: local variable 'jdk_dir' referenced before assignment`

**Comment by joelostblom** [comment]
I create a PR to try to remedy this. A [temporary workaround is specified in the arch wiki:](https://wiki.archlinux.org/index.php/Java#Silence_.27Picked_up_JAVA_OPTIONS.27_message_on_command_line)

```
_SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
unset _JAVA_OPTIONS
alias java='java "$_SILENT_JAVA_OPTIONS"'
```
