### ISSUE TITLE
pip and setup.py javabridge install error. windows 10.

### ISSUE THREAD

**Issue by HartiGit** [LeeKamentsky/python-javabridge#156]
Here is what i get : 

pip install javabridge
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\me\AppData\Local\Temp\pip-install-bbqsqval\javabridge\setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "C:\Users\me\AppData\Local\Temp\pip-install-bbqsqval\javabridge\setup.py", line 115, in ext_modules
        p = subprocess.Popen(cmd)
      File "c:\users\me\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "c:\users\me\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\me\AppData\Local\Temp\pip-install-bbqsqval\javabridge\

Any idea of what's happening. Java is install et JAVA_HOME work, as maven.

**Comment by LeeKamentsky** [comment]
Well that is bizarre - it's in code for the old mingw build. There are no tests for that and I doubt that it works (and I hope that I won't be called upon to make it work). Is there any chance you have mingw installed on that system and have the MINGW32_PREFIX, MINGW64_PREFIX or MINGW_PREFIX environment variables defined? If so, can you start a command line without them and try again? If you're using a Python within the MINGW system, it's also likely to cause this problem.

**Comment by HartiGit** [comment]
Critical Hit :)

I checked for MINGW32_PREFIX, MINGW64_PREFIX or MINGW_PREFIX in env, without results. 

Finaly ,i checked in my path, and find this "C:\MinGW\bin". I deleted it, and try to install javabridge. And it work !!! the Nosetests is OK

Thank you very much !!!

**Comment by LeeKamentsky** [comment]
Hey always glad to have a happy customer. Hope javabridge does well by you otherwise.

**Comment by mtabari** [comment]
I have the same problem and this solution worked for me by deleting MinGW directory from the user path environment. I also recommend using the same version of JDK and JRE for installing javabridge. for example, JRE 8 with JDK 8.
