### ISSUE TITLE
Can't restart VM - I have to restart IPython kernel in Spyder

### ISSUE THREAD

**Issue by nranthony** [LeeKamentsky/python-javabridge#161]
I can start and use the vm without issue the first time around:
```python
    module_fullpath = os.path.realpath("C:\\repos\\metadata code\\metadata")
    modpath, modfname = os.path.split(module_fullpath)
    bfjarpath = os.path.join(modpath, 'bioformats_package.jar')
    jars =  bioformats.JARS + [bfjarpath]
    javabridge.start_vm(class_path=jars)
```
and the vm get's used in a loop to open images with bioformats.  The trouble comes if there's an error, albeit caught in a ` try: ... except: ... `, which then stops the loop.  I thought I might be able to kill and restart the vm each loop, but it only let's me start the once, until the kernel or script is run again.

I get the following error on trying to start the second time:
```python
javabridge.kill_vm()
javabridge.start_vm()
Traceback (most recent call last):
  File "C:\Users\nellypledge\Anaconda3\lib\site-packages\javabridge\jutil.py", line 281, in start_thread
    env = vm.create(args)
  File "_javabridge.pyx", line 653, in _javabridge.JB_VM.create
RuntimeError: Failed to create Java VM. Return code = -1
Failed to create Java VM
Traceback (most recent call last):

  File "<ipython-input-5-9a63e44fb8de>", line 1, in <module>
    javabridge.start_vm()

  File "C:\Users\nellypledge\Anaconda3\lib\site-packages\javabridge\jutil.py", line 314, in start_vm
    raise RuntimeError("Failed to start Java VM")

RuntimeError: Failed to start Java VM```

Any thoughts would be much appreciated.
Thanks
Neil

**Comment by LeeKamentsky** [comment]
Hi Neil,
Yes, this is a problem, but one that we can't address - the VM can be started in a process only one time and it's a constraint in Java, not Javabridge. I hope you can reorganize your code so that the VM isn't killed if there's an exception.
The issue has already been posted (#88) - you can look there for more information.

**Comment by nranthony** [comment]
Hi Lee, thanks for the super speedy reply.
Thanks for the details...  Such is live I guess.

I've got 12 (or more) processes in python each with their own javabridge, and it's been very good except the errors stopping the associated process.  I guess I need clever error catching that doesn't crash the vm, and/or just write it in Java :)

Thanks for your time.
Neil
