### ISSUE TITLE
javabridge install fails on Windows 10

### ISSUE THREAD

**Issue by jaydoc** [LeeKamentsky/python-javabridge#167]
`  ERROR: Command errored out with exit status 1:
   command: 'c:\users\jaydoc\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jaydoc\\AppData\\Local\\Temp\\pip-install-7ps7x6zk\\javabridge\\setup.py'"'"'; __file__='"'"'C:\\Users\\jaydoc\\AppData\\Local\\Temp\\pip-install-7ps7x6zk\\javabridge\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jaydoc\AppData\Local\Temp\pip-wheel-6go6r3zb' --python-tag cp37
       cwd: C:\Users\jaydoc\AppData\Local\Temp\pip-install-7ps7x6zk\javabridge\
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\javabridge
  copying javabridge\jutil.py -> build\lib.win-amd64-3.7\javabridge
  copying javabridge\locate.py -> build\lib.win-amd64-3.7\javabridge
  copying javabridge\noseplugin.py -> build\lib.win-amd64-3.7\javabridge
  copying javabridge\wrappers.py -> build\lib.win-amd64-3.7\javabridge
  copying javabridge\_version.py -> build\lib.win-amd64-3.7\javabridge
  copying javabridge\__init__.py -> build\lib.win-amd64-3.7\javabridge
  creating build\lib.win-amd64-3.7\javabridge\tests
  copying javabridge\tests\test_cpython.py -> build\lib.win-amd64-3.7\javabridge\tests
  copying javabridge\tests\test_javabridge.py -> build\lib.win-amd64-3.7\javabridge\tests
  copying javabridge\tests\test_jutil.py -> build\lib.win-amd64-3.7\javabridge\tests
  copying javabridge\tests\test_wrappers.py -> build\lib.win-amd64-3.7\javabridge\tests
  copying javabridge\tests\__init__.py -> build\lib.win-amd64-3.7\javabridge\tests
  creating build\lib.win-amd64-3.7\javabridge\jars
  copying javabridge\jars\cpython.jar -> build\lib.win-amd64-3.7\javabridge\jars
  copying javabridge\jars\rhino-1.7R4.jar -> build\lib.win-amd64-3.7\javabridge\jars
  copying javabridge\jars\runnablequeue.jar -> build\lib.win-amd64-3.7\javabridge\jars
  copying javabridge\jars\test.jar -> build\lib.win-amd64-3.7\javabridge\jars
  running build_ext
  C:\Program Files\Java\jdk-12.0.2\bin\javac.exe -source 6 -target 6 C:\Users\jaydoc\AppData\Local\Temp\pip-install-7ps7x6zk\javabridge\java\org\cellprofiler\runnablequeue\RunnableQueue.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  error: Source option 6 is no longer supported. Use 7 or later.
  error: Target option 6 is no longer supported. Use 7 or later.
  error: command 'C:\\Program Files\\Java\\jdk-12.0.2\\bin\\javac.exe' failed with exit status 2`

I am not sure what is going wrong. I use Windows 10. 

Can someone help me fix this? Thanks..

**Comment by LeeKamentsky** [comment]
Hi Jay. I think I ran into this myself with the latest JDK installed and fixed it in 16d6c91. You might try installing the head of the master branch instead of installing from pypy:
```
pip install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip#egg=javabridge
```
Please close the issue if it works.

**Comment by jaydoc** [comment]
Hi Lee

This does work to install javabridge after I install visual C++ build tools. However, when I try to do "pip install python-bioformats" it tries to install javabridge again, and the install errors out with the same messages as earlier.

The reason I want to install javabridge is to use bioformats and cellprofiler. Not sure how to get this to work. I will however close the issue as my original problem is solved.

**Comment by yoda-vid** [comment]
> However, when I try to do "pip install python-bioformats" it tries to install javabridge again, and the install errors out with the same messages as earlier.

I've encountered this issue as well when installing from an archive rather than the Git repo itself. The installed package is given as `javabridge-0.0.0`, and Python-Bioformats ends up upgrading this package to the latest release. I think it has something to do with how `setup.py` gets the version string in [get_version](https://github.com/LeeKamentsky/python-javabridge/blob/master/setup.py#L338).

As a workaround, installing from the Git repo gives the correct version:

```
pip install git+https://github.com/LeeKamentsky/python-javabridge.git
```

with the output from the current commit:

```
Successfully installed javabridge-1.0.18.post16+gc7ccaed
```

which is kept during Python-Bioformats installation.
