### ISSUE TITLE
With JDK 12 and Python 3.8.2 the install is fails

### ISSUE THREAD

**Issue by ChrisPollini** [LeeKamentsky/python-javabridge#175]
I am trying to install javabridge so I will be able to use BioFormats for Python, but I am constatly running to this error: 

    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\javabridge
    copying javabridge\jutil.py -> build\lib.win-amd64-3.8\javabridge
    copying javabridge\locate.py -> build\lib.win-amd64-3.8\javabridge
    copying javabridge\noseplugin.py -> build\lib.win-amd64-3.8\javabridge
    copying javabridge\wrappers.py -> build\lib.win-amd64-3.8\javabridge
    copying javabridge\_version.py -> build\lib.win-amd64-3.8\javabridge
    copying javabridge\__init__.py -> build\lib.win-amd64-3.8\javabridge
    creating build\lib.win-amd64-3.8\javabridge\tests
    copying javabridge\tests\test_cpython.py -> build\lib.win-amd64-3.8\javabridge\tests
    copying javabridge\tests\test_javabridge.py -> build\lib.win-amd64-3.8\javabridge\tests
    copying javabridge\tests\test_jutil.py -> build\lib.win-amd64-3.8\javabridge\tests
    copying javabridge\tests\test_wrappers.py -> build\lib.win-amd64-3.8\javabridge\tests
    copying javabridge\tests\__init__.py -> build\lib.win-amd64-3.8\javabridge\tests
    creating build\lib.win-amd64-3.8\javabridge\jars
    copying javabridge\jars\cpython.jar -> build\lib.win-amd64-3.8\javabridge\jars
    copying javabridge\jars\rhino-1.7R4.jar -> build\lib.win-amd64-3.8\javabridge\jars
    copying javabridge\jars\runnablequeue.jar -> build\lib.win-amd64-3.8\javabridge\jars
    copying javabridge\jars\test.jar -> build\lib.win-amd64-3.8\javabridge\jars
    running build_ext
    C:\Program Files\Java\jdk-12.0.1\bin\javac.exe -source 6 -target 6 C:\Users\kovis\AppData\Local\Temp\pip-install-ue0divhz\javabridge\java\org\cellprofiler\runnablequeue\RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    error: command 'C:\\Program Files\\Java\\jdk-12.0.1\\bin\\javac.exe' failed with exit status 2

I suspect the JDK version is too high, but I have trouble getting earlier version of JDK right now. Could you elaborate what could be the problem? Thank you in advance!

**Comment by LeeKamentsky** [comment]
Can you try pip installing it from the master version on Github?

pip3 install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip#egg=python-javabridge

**Comment by ChrisPollini** [comment]
Thank you for the quick reply! I installed java bridge with the method you suggested in the comment above, it successfully installs it. Altough it says it installed javabridge 0.0.0! I assume it is still the correct version?

**Comment by LeeKamentsky** [comment]
Glad it worked for you - I have to update PyPi to get things to work out of the box. I just installed Bioformats on a machine a couple weeks ago using this method, so it should be fine for you.
