### ISSUE TITLE
Work around for jvm.start()?

### ISSUE THREAD

**Issue by MajestMed** [LeeKamentsky/python-javabridge#176]
Hello, 
So I am having the typical issue with jvm.start() where the vm cannot be started more than once. What is the workaround for this for a flask API, where I need WEKA to be used every time someone hits a specific route (/api).

On my mac I had:
```
@app.route('/api2.0/<filename>')
def qa(filename):
     jvm.start()
     WEKA EVALUATION
     jvm.stop()
     return
```

Which worked, so once I moved this to a docker container, I learned this issue with jvm, and I am struggling to figure out a solution around this?

I understand that I cannot call jvm.start() more than once, so how and where should I start the vm, is this even possible to do with the limitations? I thought I saw some people creating threads to avoid this issue?

**Comment by LeeKamentsky** [comment]
The JVM is a pretty heavy object to start on every evaluation. I think you have to figure out some way to hold a static instance to it. There are bound to be security issues to sharing a static instance among different users for a web-app, though. One possibility is to use the `multiprocessing` module to start and stop the JVM in a Python subprocess. I tested this and it works:
```
import javabridge
import multiprocessing

# Substitute whatever WEKA code you want instead of this function
def to_lower(s):
      javabridge.start_vm()
      cstring = javabridge.wrappers.JClassWrapper("java.lang.String")
      js = cstring(s)
      value = str(js.toLowerCase())
      javabridge.kill_vm()
      return value
with multiprocessing.Pool(1) as pool:
    print(pool.apply(to_lower, ["Hello, world"]))
with multiprocessing.Pool(1) as pool:
    print(pool.apply(to_lower, ["Alpha, Beta, Gamma, Delta"]))
```
This is the simplest way codewise, but I'd consider figuring out how to associate a multiprocessing.Process with each Flask application context and use multiprocessing.Pipe to send information back and forth. Inside the process's function, you might start javabridge and listen on the pipe for requests for WEKA for that user.

**Comment by MajestMed** [comment]
Thank you for getting back so quick! the quick solution you posted has worked in my code setup so thank you for being awesome. 

Do you think it would be necessary to further find a safer way if this is a rest api being called by a single machine secured by oauth?

**Comment by LeeKamentsky** [comment]
I think if you start and kill in the same process, as is done in to_lower above, it should be safe. The process along with whatever is in the Java VM will be destroyed and not accessible to another user. It just might be a bit slow, but if it works for you, it's a good solution.
