### ISSUE TITLE
DLL Load Fail

### ISSUE THREAD

**Issue by RPHennessey** [LeeKamentsky/python-javabridge#177]
Running on windows 10. Getting a DLL load failed. Looks similar to past issues but have not been able to find a solution. Error message below:

Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 11:52:54) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import weka.core.converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jehui\OneDrive\Desktop\python_venv\venv1\env3\lib\site-packages\weka\core\converters.py", line 17, in <module>
    import javabridge
  File "C:\Users\jehui\OneDrive\Desktop\python_venv\venv1\env3\lib\site-packages\javabridge\__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "C:\Users\jehui\OneDrive\Desktop\python_venv\venv1\env3\lib\site-packages\javabridge\jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: DLL load failed: The specified module could not be found.

**Comment by LeeKamentsky** [comment]
That is a little odd. You should have a file, "c:\Users\jehui\OneDrive\Desktop\python_venv\venv1\env3\lib\site-packages\javabridge\_javabridge.dll" in your system and it should have been properly loaded. If it's not there, something went wrong with the compilation during installation. If it is there, I guess you could try adding "c:\Users\jehui\OneDrive\Desktop\python_venv\venv1\env3\lib\site-packages\javabridge" to your PATH environment variable, but it  should work anyway. There may be an issue with how the DLL is packaged or maybe with the DLL finding the JVM dll on which it is dependent.

I think the first step is to check whether the dll is present and if adding the path is a quick fix. If not, the next step is to check _javabridge.dll for missing dependencies.

**Comment by DavidStirling** [comment]
I'm also seeing the same issue with Python 3.8.2 on Windows 10. I've tried a few installation methods.

It appears that the .dll file mentioned above just isn't being created at all. The only .dll in the javabridge directory is java2cpython.dll.

I previously had a working install on Python 3.7 a few months ago, so I'm not sure what's causing the problem. I have all the required compiling tools installed.
