### ISSUE TITLE
Fail to load _javabridge from javabridge\jutil.py

### ISSUE THREAD

**Issue by JoeHussar** [LeeKamentsky/python-javabridge#178]
Hello!
I am working on a project that involves BioFormats and I need Javabridge for that.
The initial tests are running onto an error (pictured below)
I installed javabridge using the pip3 command found in an earlier, closed issue.

Could you help me, what can be the problem?
![image](https://user-images.githubusercontent.com/63963331/80221492-a8bc4e80-8645-11ea-81a8-da8d9e0ad0a0.png)
Thanks in advance!

**Comment by LeeKamentsky** [comment]
Same as #177.
Do you have Cython installed? Were there any error messages when you did the PIP install? I am at a loss as to how the setup script could run and not produce a _javabridge.dll file without error. I'd appreciate it if you could uninstall and re-install Javabridge and send me the log.

I don't have access to a Windows 10 machine - if I have time, I'll try recreating this by creating a Windows 10 VM and doing the install.

**Comment by JoeHussar** [comment]
I'll be back to you with a detailed description of what we have already tried in terms of cython, jdk and c++ tools from microsoft and in what versions we tried crossmatching them! I'll compile a detailed log and environmental variables for you in a day! thx for the help so far

**Comment by LeeKamentsky** [comment]
Just checking - do you have the 64-bit version of Python installed? You should see a line like:
Python 2.7.2 (default, Jun 12 2011, 14:24:46) [MSC v.1500 64 bit (AMD64)] on win32

If it is 32-bit, it's not supported.

**Comment by DavidStirling** [comment]
Thanks for looking into this. Just to add that I've also seen this version of the error, using 64-bit Python 3. On my system installing with pip or cloning to run `python setup.py develop` produces the following error when trying to import: 
`ImportError: DLL load failed while importing _javabridge: The specified module could not be found.` 

Cloning and installing with `python setup.py install` produces 
`ModuleNotFoundError: No module named 'javabridge._javabridge'`.

I've tried rolling back Cython to 0.28 but that made no difference. In both cases it appears to generate the .c files but not the .dlls (besides java2cpython). I'm not sure what a normal log should look like, but there doesn't appear to be any attempt to build anything else.

**Comment by LeeKamentsky** [comment]
I think I'm going to leave this up to someone with more Windows experience - I am having quite a lot of difficulty configuring a 64-bit Python with a 64-bit Numpy (other than using Anaconda which is what I think I'd recommend). I would really appreciate someone coming up with a fix for this.

**Comment by DavidStirling** [comment]
Thanks for taking a look. I'm surprised Numpy is causing problems, in newer versions of Python I've been able to install it without issue using pip. I'm going to have to keep trying to solve this although I don't know much about package building. Is there a record somewhere of what the setup scripts _should_ be creating?

**Comment by DavidStirling** [comment]
Think I might have found a fix for this, I can make a pull request for this repository once we've confirmed it actually works/an actual programmer has taken a look.
