### ISSUE TITLE
JClassWrapper has thrown out an JavaException

### ISSUE THREAD

**Issue by chengweiclarence** [LeeKamentsky/python-javabridge#182]
Hi! When I run the code:
`nodi = javabridge.JClassWrapper("edu.cmu.tetrad.data.ContinuousVariable")(col)`

I get the error below:

JavaException                             Traceback (most recent call last)

<ipython-input-6-b03e087fba9f> in <module>
      2 # load dataset
      3 for col in dframe.columns:
----> 4     nodi = javabridge.JClassWrapper("edu.cmu.tetrad.data.ContinuousVariable")(col)
      5     node_list.add(nodi)

c:\users\sx-liang\appdata\local\programs\python\python37\lib\site-packages\javabridge\wrappers.py in __init__(self, class_name)
    229         STATIC = J.get_static_field("java/lang/reflect/Modifier", "STATIC", "I")
    230         self.cname = class_name.replace(".", "/")
--> 231         self.klass = J.get_class_wrapper(J.class_for_name(class_name), True)
    232         self.static_methods = {}
    233         env = J.get_env()

c:\users\sx-liang\appdata\local\programs\python\python37\lib\site-packages\javabridge\jutil.py in class_for_name(classname, ldr)
   1746                        '(Ljava/lang/String;ZLjava/lang/ClassLoader;)'
   1747                        'Ljava/lang/Class;',
-> 1748                        classname, True, ldr)
   1749 
   1750 def get_class_wrapper(obj, is_class = False):

c:\users\sx-liang\appdata\local\programs\python\python37\lib\site-packages\javabridge\jutil.py in static_call(class_name, method_name, sig, *args)
    941     ret_sig = sig[sig.find(')')+1:]
    942     nice_args = get_nice_args(args, args_sig)
--> 943     result = fn(*nice_args)
    944     return get_nice_result(result, ret_sig)
    945 

c:\users\sx-liang\appdata\local\programs\python\python37\lib\site-packages\javabridge\jutil.py in fn(*args)
    921         jexception = env.exception_occurred()
    922         if jexception is not None:
--> 923             raise JavaException(jexception)
    924         return result
    925     return fn

JavaException: edu.cmu.tetrad.data.ContinuousVariable 

Should I check my Internet settings or pre-download the necessary package? If I need to pre-download the necessary package, where should it be put?

Thanks in advance!

**Comment by LeeKamentsky** [comment]
Hi, CWC. The trick here is to make sure that the JAR file which has the code for edu.cmu.tetrad.data.ContinuousVariable is on the classpath during the call that starts Javabridge, for instance, if the JAR is at `/path-to/myjar.jar`:

```python
import javabridge
javabridge.start_vm(classpath=javabridge.JARS + [`/path-to`]
...
javabridge.kill_vm()
```
Let me know if this helps and if it does, please close the issue.

--Lee

**Comment by chengweiclarence** [comment]
Hi, Lee! I have successfully solved this problem. Thanks very much!

**Comment by LeeKamentsky** [comment]
Enjoy! Thx for getting back to me.
