### ISSUE TITLE
"File not found" for the python executable when installing on Windows

### ISSUE THREAD

**Issue by sevaa** [LeeKamentsky/python-javabridge#186]
Windows 10 x64, freshly installed Python 3.9 x64. Trying `pip install javabridge` gives the following error:

> C:\WINDOWS\system32>pip install javabridge
> Collecting javabridge
>   Using cached javabridge-1.0.19.tar.gz (1.3 MB)
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tee20wzq\\javabridge\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tee20wzq\\javabridge\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\me\AppData\Local\Temp\pip-pip-egg-info-7kmxbqu1'
>          cwd: C:\Users\me\AppData\Local\Temp\pip-install-tee20wzq\javabridge\
>     Complete output (11 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\me\AppData\Local\Temp\pip-install-tee20wzq\javabridge\setup.py", line 406, in <module>
>         ext_modules=ext_modules(),
>       File "C:\Users\me\AppData\Local\Temp\pip-install-tee20wzq\javabridge\setup.py", line 119, in ext_modules
>         p = subprocess.Popen(cmd)
>       File "c:\python39\lib\subprocess.py", line 947, in __init__
>         self._execute_child(args, executable, preexec_fn, close_fds,
>       File "c:\python39\lib\subprocess.py", line 1416, in _execute_child
>         hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>     FileNotFoundError: [WinError 2] The system cannot find the file specified
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The reason could be that single quotes don't work in the Windows command line as the package expects. Running `'c:\python39\python.exe'` (sic) on the command line gives an error message.

**Comment by LeeKamentsky** [comment]
Hi Seva. That exception took place in code that's specific for a Windows installation running in a Mingw32 or Mingw64 shell. You should look at the install steps here:
https://github.com/LeeKamentsky/python-javabridge/blob/master/docs/installation.rst#windows

I no longer have a Windows machine to test on, so I can't confirm that the directions given there are current. The directions do need to be updated to Python 3.x.

**Comment by sevaa** [comment]
I have Visual C++ installed (but not Mingw). There's nothing in the Windows section about feeding the compiler path to the install script, and/or telling it to use Visual C++. Tried running with VC++ CLI tools in path - same result.

**Comment by LeeKamentsky** [comment]
The logic for the is_mingw check is here: https://github.com/LeeKamentsky/python-javabridge/blob/master/javabridge/locate.py#L25

If you have "DISTUTILS_USE_SDK" or "MSSdk" defined in your environment, then it should use the VC tools. I have manually set DISTUTILS_USE_SDK=1 in the past to force that code path and that might work for you. It still should use the SDK unless you have MINGW32_PREFIX or MINGW64_PREFIX defined or if you have some program named "gdd" on your path.

Hope this helps. I would try setting DISTUTILS_USE_SDK as a work-around.

**Comment by sevaa** [comment]
Worked with:

 - Visual Studio 2019 (in my case) command prompt for x64, to match the Python and JDK bitness
 - `set DISTUTILS_USE_SDK=1`
 - Elevation

Thank you!

**Comment by LeeKamentsky** [comment]
Thank goodness. Enjoy.
