### ISSUE TITLE
Incompatibility with python 3.11

### ISSUE THREAD

**Issue by thosoo** [LeeKamentsky/python-javabridge#209]
You will get an error with
'longintrepr.h': No such file or directory
during pip install with python 3.11

**Comment by LeeKamentsky** [comment]
Unfortunately, I am unable to  update Javabridge on PyPi. Please try installing using:
```
pip3 install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip#egg=javabridge
```
I was able to successfully do so in a Conda environment on Ubuntu using Python 3.11
Feel free to reopen if this doesn't work.

**Comment by bmh2127** [comment]
Processing /home/sa-dev/python-javabridge
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages (from javabridge==1.0.19.post9+gc8c12b4) (1.26.4)
Building wheels for collected packages: javabridge
  Building wheel for javabridge (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [283 lines of output]
      /home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/_version.py -> build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/noseplugin.py -> build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/__init__.py -> build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/jutil.py -> build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/wrappers.py -> build/lib.linux-x86_64-cpython-311/javabridge
      copying javabridge/locate.py -> build/lib.linux-x86_64-cpython-311/javabridge
      creating build/lib.linux-x86_64-cpython-311/javabridge/tests
      copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-cpython-311/javabridge/tests
      copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-cpython-311/javabridge/tests
      copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-cpython-311/javabridge/tests
      copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-cpython-311/javabridge/tests
      copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-cpython-311/javabridge/tests
      creating build/lib.linux-x86_64-cpython-311/javabridge/jars
      copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-cpython-311/javabridge/jars
      running build_ext
      javac /home/sa-dev/python-javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
      jar cf /home/sa-dev/python-javabridge/build/lib.linux-x86_64-cpython-311/javabridge/jars/runnablequeue.jar -C /home/sa-dev/python-javabridge/java org/cellprofiler/runnablequeue/RunnableQueue.class -C /home/sa-dev/python-javabridge/java org/cellprofiler/runnablequeue/RunnableQueue$1.class
      javac /home/sa-dev/python-javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
      jar cf /home/sa-dev/python-javabridge/build/lib.linux-x86_64-cpython-311/javabridge/jars/test.jar -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/test/RealRect.class
      javac /home/sa-dev/python-javabridge/java/org/cellprofiler/javabridge/CPython.java /home/sa-dev/python-javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
      Note: /home/sa-dev/python-javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
      jar cf /home/sa-dev/python-javabridge/build/lib.linux-x86_64-cpython-311/javabridge/jars/cpython.jar -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/CPythonInvocationHandler.class -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/CPython$StackFrame.class -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/CPython$WrappedException.class -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/CPython.class -C /home/sa-dev/python-javabridge/java org/cellprofiler/javabridge/CPythonInvocationHandler.class
      warning: _javabridge_osspecific.pxd:12:4: 'JavaVMOption' redeclared
      warning: _javabridge_osspecific.pxd:19:4: 'JavaVMInitArgs' redeclared
      warning: _javabridge.pyx:94:4: 'jvalue' redeclared
      warning: _javabridge.pyx:112:4: 'JavaVMOption' redeclared
      warning: _javabridge.pyx:119:4: 'JavaVMInitArgs' redeclared
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge.pyx:373:0: Global name __dead_objects matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: _javabridge_osspecific.pxd:12:4: 'JavaVMOption' redeclared
      warning: _javabridge_osspecific.pxd:19:4: 'JavaVMInitArgs' redeclared
      warning: _javabridge_mac.pyx:4:4: 'jint' redeclared
      warning: _javabridge_mac.pyx:5:4: 'jboolean' redeclared
      warning: _javabridge_mac.pyx:9:4: 'JavaVM' redeclared
      warning: _javabridge_mac.pyx:14:4: 'JavaVMOption' redeclared
      warning: _javabridge_mac.pyx:21:4: 'JavaVMInitArgs' redeclared
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          void MacRunLoopStop() nogil
          void MacRunLoopReset() nogil
          int MacIsMainThread() nogil
          void MacRunLoopRunInMode(double) nogil
      
      cdef void StopVM(JavaVM *vm):
           ^
      ------------------------------------------------------------
      
      _javabridge_mac.pyx:34:5: Function signature does not match previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
           MacStopVM()
      
      #
      # Unused stub in Mac
      #
      cdef int CreateJavaVM(JavaVM **pvm, void **pEnv, void *args):
           ^
      ------------------------------------------------------------
      
      _javabridge_mac.pyx:40:5: Function signature does not match previous declaration
      warning: _javabridge_nomac.pxd:15:4: 'JavaVMInitArgs' redeclared
      warning: _javabridge_nomac.pxd:20:4: 'JavaVMOption' redeclared
      warning: _javabridge_nomac.pyx:4:4: 'jint' redeclared
      warning: _javabridge_nomac.pyx:5:4: 'jboolean' redeclared
      warning: _javabridge_nomac.pyx:9:4: 'JavaVM' redeclared
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
               jint (*DetachCurrentThread)(JavaVM *vm) nogil
               jint (*GetEnv)(JavaVM *vm, void **penv, jint version) nogil
               jint (*AttachCurrentThreadAsDaemon)(JavaVM *vm, void *penv, void *args) nogil
          jint JNI_CreateJavaVM(JavaVM **pvm, void **penv, void *args) nogil
      
      cdef int MacStartVM(JavaVM **pvm, JavaVMInitArgs *pVMArgs, char *class_name) nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:19:5: Function signature does not match previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          jint JNI_CreateJavaVM(JavaVM **pvm, void **penv, void *args) nogil
      
      cdef int MacStartVM(JavaVM **pvm, JavaVMInitArgs *pVMArgs, char *class_name) nogil:
          return -1
      
      cdef void StopVM(JavaVM *vm) nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:22:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:22:5: Exception check on 'StopVM' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'StopVM' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'StopVM' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          return -1
      
      cdef void StopVM(JavaVM *vm) nogil:
          vm[0].DestroyJavaVM(vm)
      
      cdef void MacRunLoopInit() nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:25:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:25:5: Exception check on 'MacRunLoopInit' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'MacRunLoopInit' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'MacRunLoopInit' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          vm[0].DestroyJavaVM(vm)
      
      cdef void MacRunLoopInit() nogil:
          pass
      
      cdef void MacRunLoopRun() nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:28:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:28:5: Exception check on 'MacRunLoopRun' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'MacRunLoopRun' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'MacRunLoopRun' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          pass
      
      cdef void MacRunLoopRun() nogil:
          pass
      
      cdef void MacRunLoopStop() nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:31:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:31:5: Exception check on 'MacRunLoopStop' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'MacRunLoopStop' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'MacRunLoopStop' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          pass
      
      cdef void MacRunLoopStop() nogil:
          pass
      
      cdef void MacRunLoopReset() nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:34:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:34:5: Exception check on 'MacRunLoopReset' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'MacRunLoopReset' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'MacRunLoopReset' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          pass
      
      cdef void MacRunLoopReset() nogil:
          pass
      
      cdef int MacIsMainThread() nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:37:5: Function signature does not match previous declaration
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          pass
      
      cdef int MacIsMainThread() nogil:
          return 0
      
      cdef void MacRunLoopRunInMode(double timeout) nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:40:5: Function signature does not match previous declaration
      performance hint: _javabridge_nomac.pyx:40:5: Exception check on 'MacRunLoopRunInMode' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'MacRunLoopRunInMode' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'MacRunLoopRunInMode' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          return 0
      
      cdef void MacRunLoopRunInMode(double timeout) nogil:
          pass
      
      cdef int CreateJavaVM(JavaVM **pvm, void **pEnv, void *args) nogil:
           ^
      ------------------------------------------------------------
      
      _javabridge_nomac.pyx:43:5: Function signature does not match previous declaration
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sa-dev/python-javabridge/setup.py", line 382, in <module>
          setup(name="javabridge",
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sa-dev/python-javabridge/setup.py", line 189, in run
          result = build_cython()
                   ^^^^^^^^^^^^^^
        File "/home/sa-dev/python-javabridge/setup.py", line 62, in build_cython
          subprocess.check_call(cmd, env=env)
        File "/home/sa-dev/anaconda3/envs/lct-napari/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/sa-dev/anaconda3/envs/lct-napari/bin/python3.11', '-m', 'cython', '-3', '/home/sa-dev/python-javabridge/_javabridge.pyx', '/home/sa-dev/python-javabridge/_javabridge_mac.pyx', '/home/sa-dev/python-javabridge/_javabridge_nomac.pyx']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for javabridge
  Running setup.py clean for javabridge
Failed to build javabridge
