### ISSUE TITLE
using JClassWrapper has an error:   javabridge.jutil.JavaException: net.lifove.clami.util.*

### ISSUE THREAD

**Issue by wxyzjp123** [LeeKamentsky/python-javabridge#211]
the code : Utils = weka.core.classes.JClassWrapper('net.lifove.clami.util.*')

even i have add the net.jar path such as javabridge.start_vm(class_path=javabridge.JARS + ['/Users/we/Desktop/net.jar'])

**Comment by LeeKamentsky** [comment]
The wildcard won't work. You have to specify the single class name exactly
