### ISSUE TITLE
DLL load failed - the specified module could not be found

### ISSUE THREAD

**Issue by LeeKamentsky** [LeeKamentsky/python-javabridge#67]
The following stack trace on Windows after Javabridge install:

    Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on w
n32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import javabridge
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "e:\venv\javabridge\lib\site-packages\javabridge-1.0.11_21_g7114a7d-py2.
-win-amd64.egg\javabridge\__init__.py", line 28, in <module>
        from .jutil import start_vm, kill_vm, activate_awt, deactivate_awt
      File "e:\venv\javabridge\lib\site-packages\javabridge-1.0.11_21_g7114a7d-py2.
-win-amd64.egg\javabridge\jutil.py", line 138, in <module>
        import _javabridge
    ImportError: DLL load failed: The specified module could not be found.
    >>>

This machine did not have msvcr100.dll installed globally (e.g. c:\Windows\System32\msvcr100.dll). There is a copy in the bin directory of the JRE and if that is added to the path, javabridge loads. The following is a work-around:

    >>> import ctypes
    >>> ctypes.cdll.LoadLibrary(r"C:\Program Files\Java\jre1.8.0_65\bin\msvcr100.dll
")
    <CDLL 'C:\Program Files\Java\jre1.8.0_65\bin\msvcr100.dll', handle 6b3e0000 at 1
f29a58>
    >>> import javabridge
    >>>

**Comment by jbcoe** [comment]
I think this issue can be closed: https://github.com/LeeKamentsky/python-javabridge/pull/66 says it fixes the issue.
