### ISSUE TITLE
OSX Java VM Problem

### ISSUE THREAD

**Issue by rhoerbe** [LeeKamentsky/python-javabridge#78]
While installing javabridge on OSX 10.11 I encounted 2 problems:
(1) Failed to execute "find'" when searching for libjvm.
The reason is a py2/3 str/bytes issue in jutil/_find_mac_lib(). I submitted  PR #77 for the fix.
(2) subsequential, I run into this:
```
import os
import javabridge
with javabridge.vm(run_headless=True):
    print(javabridge.run_script('java.lang.String.format("Hello, %s!", greetee);', dict(greetee='world')))
>>> >>> >>> ... 
... Traceback (most recent call last):
  File "/Users/admin/virtualenvs/test34/lib/python3.4/site-packages/javabridge-1.0.14-py3.4-macosx-10.11-x86_64.egg/javabridge/jutil.py", line 277, in start_thread
    vm.create_mac(args, RQCLS, library_path, libjli_path)
  File "_javabridge.pyx", line 650, in _javabridge.JB_VM.create_mac (_javabridge.c:6956)
TypeError: expected bytes, str found
Failed to create Java VM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/admin/virtualenvs/test34/lib/python3.4/site-packages/javabridge-1.0.14-py3.4-macosx-10.11-x86_64.egg/javabridge/jutil.py", line 193, in __enter__
    start_vm(*self.args, **self.kwds)
  File "/Users/admin/virtualenvs/test34/lib/python3.4/site-packages/javabridge-1.0.14-py3.4-macosx-10.11-x86_64.egg/javabridge/jutil.py", line 314, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```

**Comment by LeeKamentsky** [comment]
fixed by e97a0c2

**Comment by rhoerbe** [comment]
My PR fixed only the first issue, I am stuck with the second one.

**Comment by LeeKamentsky** [comment]
Rats - I don't have a Mac. The arguments to JB_VM.create_mac need to be encoded as `bytes`. I can push a PR, but maybe you can test after I do?

**Comment by rhoerbe** [comment]
Yes, I will do

**Comment by rhoerbe** [comment]
let me know which branch

**Comment by rhoerbe** [comment]
Ah, I understand,you are sending a PR to my fork instead of branching

**Comment by LeeKamentsky** [comment]
Nope - doing a pr on your branch would have been better, esp if I hadn't merged. But I didn't. Here's the PR.
https://github.com/LeeKamentsky/python-javabridge/pull/79

**Comment by rhoerbe** [comment]
The change in your PR did the job with MacPorts py34. Thanks.

**Comment by rhoerbe** [comment]
What test env are you using?

**Comment by LeeKamentsky** [comment]
nose. The docs for running are here:
https://github.com/LeeKamentsky/python-javabridge/blob/master/docs/unittesting.rst
