### ISSUE TITLE
Cannot static call java.nio.file.Paths with a get method

### ISSUE THREAD

**Issue by chirayukong** [LeeKamentsky/python-javabridge#81]
I try to create a Path object using a get static call from java.nio.file.Paths class with java.net.URI object parameter and get an error:

>>> jstr = javabridge.make_instance("java/lang/String","(Ljava/lang/String;)V",temp_data_path)
>>> uri = javabridge.make_instance("java/net/URI","(Ljava/lang/String;)V",jstr)
>>> f = javabridge.static_call("java/nio/file/Paths","get","(Ljava/net/URI;)V",uri)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/javabridge-1.0.11_26_g19ba020-py2.7-macosx-10.6-intel.egg/javabridge/jutil.py", line 920, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/javabridge-1.0.11_26_g19ba020-py2.7-macosx-10.6-intel.egg/javabridge/jutil.py", line 899, in make_static_call
    'with signature = %s' %(method_name, sig))
javabridge.jutil.JavaError: Could not find method name = get with signature = (Ljava/net/URI;)V

Any thought?

**Comment by LeeKamentsky** [comment]
The signature is missing the return value. It should be `(Ljava/net/URI;)Ljava/nio/file/Path;` I believe (although I haven't tried it). Also you might try:

    import javabridge
    uri = javabridge.JClassWrapper('java.net.URI')("http://example.com"))
    f = javabridge.JClassWrapper('java.nio.file.Paths').get(uri)

I haven't actually tried the above (away from the office), but barring some possible typos, it should be a lot simpler for you.

**Comment by chirayukong** [comment]
Thanks a lot for a prompt reply. It works. JClassWrapper makes my life easier. :-)

**Comment by LeeKamentsky** [comment]
Glad to hear it - have fun.
