### ISSUE TITLE
Make Java collections iterable and indexable in Python

### ISSUE THREAD

**Issue by jbcoe** [LeeKamentsky/python-javabridge#83]
I'd like the following code to work

```
javabridge.start_vm(run_headless=True)
a = javabridge.JClassWrapper('java.util.ArrayList')()
a.add(1)
a.add(2)

for x in a:
  print a

assert len(a) == 2
assert a[0] == 1
```

I'm happy to try and implement this but would need some strong guidance in how to get started.

**Comment by LeeKamentsky** [comment]
Hi  @jbcoe,
If you wanted to do this, the direction I would take:
* `a` above is an instance of `javabridge.JWrapper`.
* The `java.util.ArrayList` class is iterable, so you can call `a.iterator()` to get the iterable and then use `next()` and `hasNext()` to iterate the values.
* You can override javabridge.JWrapper.__iter__ and inside check to see if the Java object implements java.util.Iterable (or maybe just call `a.iterator() and let the exception be raised). This should return a Python object that follows the Python iterator pattern (https://docs.python.org/2/library/stdtypes.html#iterator-types).

So those are my thoughts in a nutshell, thanks for taking this on, give it a go and submit a pull request and we'll talk further. Oh... and extra points for you if you write a unit test.

--Lee
