### ISSUE TITLE
How to define a listener with 2 functions for call back

### ISSUE THREAD

**Issue by narasing** [LeeKamentsky/python-javabridge#91]
Hi I would like to know how I can specify MessageLIsteners to listen to messages 
        MessageListener responseMessageListener = new MessageListener()
        {
            @Override
            public void onMessage(ResponseMessage message) {

                System.out.println("Inside OnMessage: " + message);
            }

            @Override
            public void onException(Exception ex) {
                System.err.println("Exception in OnMessage: " + ExceptionUtils.getStackTrace(ex));
            }
        };

This listener object responseMessageListener is passed to a function.

**Comment by narasing** [comment]
MessageListener is an Interface & onMessage is called with a ResponseMessage as you can see.

**Comment by LeeKamentsky** [comment]
You should look at JProxy (https://github.com/LeeKamentsky/python-javabridge/blob/master/javabridge/wrappers.py#L356) for the coolest way to write a listener that binds Python code to a Java method, such as your "onException". However, practically speaking, a little Javascript is often the quickest way to get things done. See https://github.com/LeeKamentsky/python-javabridge/blob/master/demo/demo_uicallback.py for an example that creates a callback in Javascript that communicates with a Python thread via queues.

**Comment by narasing** [comment]
Thank you. I will try option 1 .

**Comment by narasing** [comment]
This worked perfectly. Thank you.

**Comment by LeeKamentsky** [comment]
Enjoy, thanks for using Javabridge.
