### ISSUE TITLE
can not install on raspbian over raspberry

### ISSUE THREAD

**Issue by deepzf** [LeeKamentsky/python-javabridge#93]
running install
running bdist_egg
running egg_info
creating javabridge.egg-info
writing requirements to javabridge.egg-info/requires.txt
writing javabridge.egg-info/PKG-INFO
writing top-level names to javabridge.egg-info/top_level.txt
writing dependency_links to javabridge.egg-info/dependency_links.txt
writing entry points to javabridge.egg-info/entry_points.txt
writing manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '_javabridge.c'
warning: no files found matching '_javabridge_mac.c'
warning: no files found matching '_javabridge_nomac.c'
no previously-included directories found matching '*.pyx'
writing manifest file 'javabridge.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/javabridge
copying javabridge/__init__.py -> build/lib.linux-armv7l-2.7/javabridge
copying javabridge/noseplugin.py -> build/lib.linux-armv7l-2.7/javabridge
copying javabridge/jutil.py -> build/lib.linux-armv7l-2.7/javabridge
copying javabridge/_version.py -> build/lib.linux-armv7l-2.7/javabridge
copying javabridge/wrappers.py -> build/lib.linux-armv7l-2.7/javabridge
copying javabridge/locate.py -> build/lib.linux-armv7l-2.7/javabridge
creating build/lib.linux-armv7l-2.7/javabridge/tests
copying javabridge/tests/test_cpython.py -> build/lib.linux-armv7l-2.7/javabridge/tests
copying javabridge/tests/__init__.py -> build/lib.linux-armv7l-2.7/javabridge/tests
copying javabridge/tests/test_wrappers.py -> build/lib.linux-armv7l-2.7/javabridge/tests
copying javabridge/tests/test_javabridge.py -> build/lib.linux-armv7l-2.7/javabridge/tests
copying javabridge/tests/test_jutil.py -> build/lib.linux-armv7l-2.7/javabridge/tests
creating build/lib.linux-armv7l-2.7/javabridge/jars
copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-armv7l-2.7/javabridge/jars
running build_ext
javac -source 6 -target 6 java/org/cellprofiler/runnablequeue/RunnableQueue.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
jar cf build/lib.linux-armv7l-2.7/javabridge/jars/runnablequeue.jar -C java org/cellprofiler/runnablequeue/RunnableQueue.class -C java org/cellprofiler/runnablequeue/RunnableQueue$1.class
javac -source 6 -target 6 java/org/cellprofiler/javabridge/test/RealRect.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
jar cf build/lib.linux-armv7l-2.7/javabridge/jars/test.jar -C java org/cellprofiler/javabridge/test/RealRect.class
javac -source 6 -target 6 java/org/cellprofiler/javabridge/CPython.java java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
jar cf build/lib.linux-armv7l-2.7/javabridge/jars/cpython.jar -C java org/cellprofiler/javabridge/CPython$WrappedException.class -C java org/cellprofiler/javabridge/CPythonInvocationHandler.class -C java org/cellprofiler/javabridge/CPython.class -C java org/cellprofiler/javabridge/CPython$StackFrame.class -C java org/cellprofiler/javabridge/CPythonInvocationHandler.class
building 'javabridge._javabridge' extension
creating build/temp.linux-armv7l-2.7
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/jvm/java-7-openjdk-armhf/include -I/usr/lib/jvm/java-7-openjdk-armhf/include/linux -I/usr/include/python2.7 -c _javabridge.c -o build/temp.linux-armv7l-2.7/_javabridge.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from _javabridge.c:239:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from _javabridge.c:242:0:
mac_javabridge_utils.h:47:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT void MacStopVM();
 ^
mac_javabridge_utils.h:55:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT void MacRunLoopInit();
 ^
mac_javabridge_utils.h:63:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT void MacRunLoopRun();
 ^
mac_javabridge_utils.h:71:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT void MacRunLoopReset();
 ^
mac_javabridge_utils.h:79:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT void MacStopRunLoop();
 ^
mac_javabridge_utils.h:88:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 JNIEXPORT int MacIsMainThread();
 ^
mac_javabridge_utils.h:103:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void MacRunLoopStop();
 ^
_javabridge.c: In function ‘__pyx_pf_11_javabridge_5JB_VM_2create’:
_javabridge.c:6280:3: warning: implicit declaration of function ‘CreateJavaVM’ [-Wimplicit-function-declaration]
   __pyx_t_3 = __Pyx_PyInt_From_int(CreateJavaVM((&__pyx_v_self->vm), ((void **)(&__pyx_v_env)), (&__pyx_v_args))); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 619; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
   ^
_javabridge.c: In function ‘__pyx_pf_11_javabridge_5JB_VM_12destroy’:
_javabridge.c:7339:5: warning: implicit declaration of function ‘StopVM’ [-Wimplicit-function-declaration]
     StopVM(__pyx_v_self->vm);
     ^
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:327:0,
                 from _javabridge.c:240:
_javabridge.c: At top level:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/jvm/java-7-openjdk-armhf/include -I/usr/lib/jvm/java-7-openjdk-armhf/include/linux -I/usr/include/python2.7 -c _javabridge_nomac.c -o build/temp.linux-armv7l-2.7/_javabridge_nomac.o
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/_javabridge.o build/temp.linux-armv7l-2.7/_javabridge_nomac.o -L/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/amd64/client -L/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/amd64/server -L/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/i386/client -L/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/i386/server -Wl,-R/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/amd64/client -Wl,-R/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/amd64/server -Wl,-R/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/i386/client -Wl,-R/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/i386/server -ljvm -o build/lib.linux-armv7l-2.7/javabridge/_javabridge.so
/usr/bin/ld: cannot find -ljvm
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by LeeKamentsky** [comment]
I think you're the first to try on an ARM, @deepzf.  Could you do:

    ls /usr/lib/jvm/java-7-openjdk-armhf/jre/lib

for me? There should be a processor-specific library, something like  `arm`

If you could try editing this line here: https://github.com/LeeKamentsky/python-javabridge/blob/master/setup.py#L137

    for arch in ['amd64', 'i386']

and add `arm` to that list (or whatever similar directory contains server/libjvm.so) and try again, I'd appreciate and will patch.

**Comment by deepzf** [comment]
Great! it worked! THX!

**Comment by LeeKamentsky** [comment]
If you want to be immortalized in the repo, send me a pull request with the fix.

**Comment by deepzf** [comment]
Ok,l will do some test first.
