### ISSUE TITLE
How to pass a Enum object as argument in a method? 

### ISSUE THREAD

**Issue by narasing** [LeeKamentsky/python-javabridge#94]
public enum Alignment { LEFT, RIGHT }
some method: callFunction(Alighnment.LEFT)
Signature: (Lcom/company/Alignment)V

I need to pass Alignment.LEFT or Alignment.RIGHT as argument to a function. 

 I tried the following: 
 mstate = javabridge.make_instance("java/util/Hashtable", "()V")
javabridge.call(mstate, "put","(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;","LEFT", "Left")
states = javabridge.call(mstate, "keys", "()Ljava/util/Enumeration;")
stateenums = javabridge.get_class_wrapper(states)
state  = javabridge.call(stateenums, "nextElement", "()Ljava/lang/Object;")

object.callFunction(state)

No matching method found callFunction.

How can I pass this?

**Comment by narasing** [comment]
Doing this gives me this error; 
>>> stateenums = javabridge.get_class_wrapper(state)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\enthought\canopy\user\lib\site-packages\javabridge\jutil.py", line 17
79, in get_class_wrapper
    class_object = call(obj, 'getClass','()Ljava/lang/Class;')
  File "c:\enthought\canopy\user\lib\site-packages\javabridge\jutil.py", line 88
1, in call
    fn = make_call(o, method_name, sig)
  File "c:\enthought\canopy\user\lib\site-packages\javabridge\jutil.py", line 83
5, in make_call
    klass = env.get_object_class(o)
TypeError: Argument 'o' has incorrect type (expected _javabridge.JB_Object, got
Enumeration)
>>>
It seems to correctly identify the object as of type Enumeration, then why its not able to find the signature?

**Comment by narasing** [comment]
is there a more elegent way to get the type of the object being passed to check against the signature? 

Also unable to do mstatep = javabridge.make_instance("com/company/Alignment", "()V") and unable to pass stateenums( = javabridge.get_class_wrapper(states) ).getting  TypeError: Argument 'o' has incorrect type (expected _javabridge.JB_Object, got
Klass)

**Comment by LeeKamentsky** [comment]
Maybe you should try the more modern approach. This worked for me:

     import javabridge
     javabridge.start_vm()
     drop_mode = javabridge.JClassWrapper("javax.swing.DropMode")
     insert = drop_mode.INSERT
     tbl = javabridge.JClassWrapper("javax.swing.JTable")()
     tbl.setDropMode(insert)

Would that work for you?

**Comment by narasing** [comment]
Sorry by replacing this : 
stateenums = javabridge.get_class_wrapper(states)
to 
stateenums = javabridge.get_enumeration_wrapper(states)

I am able to get the state as Enumeration Interface.But still isnt working .how to get enum datatype?

**Comment by narasing** [comment]
let me try what you suggested. Thanks

**Comment by narasing** [comment]
if drop_mode is an Enumeration object, how would you specify drop_mode.INSERT as I am getting AttributeError: 'Enumeration' object has no attribute 'INSERT'

**Comment by narasing** [comment]
Sorry, your suggestion worked like a charm. Thank you.
