### ISSUE TITLE
Error creating Java VM

### ISSUE THREAD

**Issue by Heerpa** [LeeKamentsky/python-javabridge#96]
Hi!
I am trying to use bio formats for python which uses javabridge, and am working on a Mac OS X. There are a few issues, though, unfortunately.
I have Java JDK installed

$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home

and installed javabridge using 
pip install javabridge

when trying the test code
>>> import javabridge
>>> import bioformats
>>> javabridge.start_vm(class_path=bioformats.JARS)

I got the Error that the Java VM could not be started:
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.5/site-packages/javabridge/jutil.py", line 116, in _find_mac_lib
    lines = result.split("\n")

being pointed by this post,
https://groups.google.com/forum/#!topic/python-weka-wrapper/g7eux33sjak
I tried to download javabridge from here and directly install it, which gave me (admin user) a permission error:
Adding javabridge 0.0.0 to easy-install.pth file
error: [Errno 13] Permission denied: '/Users/grabmayr/anaconda/lib/python3.5/site-packages/easy-install.pth'
So, I installed while being logged in as the root user. Switching back to my standard user, I found nothing had changed, really (unsurprisingly, I guess, because it had been installed for a different user - but people keep writing that you should do that.) I also tried using "sudo pyhton setup.py install", and here I get the error:
gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/grabmayr/anaconda/include -arch x86_64 -I/Users/grabmayr/anaconda/include/python3.5m -Ijava -I/System/Library/Frameworks/JavaVM.Framework/Headers -I/Users/grabmayr/anaconda/include/python3.5m -c java/org_cellprofiler_javabridge_CPython.c -o build/temp.macosx-10.5-x86_64-3.5/java/org_cellprofiler_javabridge_CPython.o
java/org_cellprofiler_javabridge_CPython.c:10:10: fatal error: 'jni.h' file not
      found
#include <jni.h>

As for my user before setting JAVA_HOME in .bash_profile, but "sudo echo $JAVA_HOME" returns the same as without sudo, so I guess the system variable should be seen. Calling 
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
in analogy to a previous thread here did not help either.
So I replaced the pip-version of jutil.py by the downloaded one, which resulted in a new traceback:

Traceback (most recent call last):
  File "/Users/grabmayr/anaconda/lib/python3.5/site-packages/javabridge/jutil.py", line 268, in start_thread
    vm.create_mac(args, RQCLS, library_path, libjli_path)
  File "_javabridge.pyx", line 650, in _javabridge.JB_VM.create_mac (_javabridge.c:6878)
TypeError: expected bytes, str found
Failed to create Java VM

But I could not locate"_javabridge.pyx" to do the same there.

I am now at a dead end, and help would be greatly appreciated.

Thanks
  - Heinrich

**Comment by LeeKamentsky** [comment]
Hi Heirich - unfortunately, you might be the first person to install Javabridge for 3.x on the Mac. It looks like you are running into something caused by the 2.x -> 3.x incompatibilities that we failed to change when doing the 3.x support. Let me take a look at it and maybe give you a patch to try out.

Regarding the install, especially with Anaconda, I would create a virtual environment and install Javabridge in that virtual environment  - that will keep you from having to use Sudo to do the install and things should be much cleaner for you.

**Comment by LeeKamentsky** [comment]
Oops - duplicate of https://github.com/LeeKamentsky/python-javabridge/issues/78

This fixes it: https://github.com/LeeKamentsky/python-javabridge/commit/8c807275614c4f8d96aa90bcf17f8e28ce9e69b7

Need to do a release to PyPi, but you should be able to install like this:

pip install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip

Please close if this fixes it.

**Comment by Heerpa** [comment]
Thanks very much also for the comment about virtual environments.
Sorry for this basic question, but the way I have understood these virtual environments, they exist for anaconda, so that I can use different versions of python and packages. How does this help for me to download and directly install your python javabridge master? I tried it with the following result:

(MyEnv) pcju21:python-javabridge-master grabmayr$ python setup.py install
running install
running bdist_egg
....
Extracting javabridge-0.0.0-py3.5-macosx-10.6-x86_64.egg to /Users/grabmayr/anaconda/envs/MyEnv/lib/python3.5/site-packages
Adding javabridge 0.0.0 to easy-install.pth file

Installed /Users/grabmayr/anaconda/envs/MyEnv/lib/python3.5/site-packages/javabridge-0.0.0-py3.5-macosx-10.6-x86_64.egg
Processing dependencies for javabridge==0.0.0
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Adding numpy 1.11.1 to easy-install.pth file

Using /Users/grabmayr/anaconda/envs/MyEnv/lib/python3.5/site-packages
Finished processing dependencies for javabridge==0.0.0


So that seemed to work. For testing, I opened ipython:
$ ipython
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
Type "copyright", "credits" or "license" for more information.


and imported javabridge, which resulted in an error:
In [1]: import javabridge
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3e086c0476fa> in <module>()
----> 1 import javabridge

/Users/grabmayr/.Trash/python-javabridge-master 16.40.14/javabridge/__init__.py in <module>()
     26 
     27 
---> 28 from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
     29 
     30 from .jutil import attach, detach, get_env

/Users/grabmayr/.Trash/python-javabridge-master 16.40.14/javabridge/jutil.py in <module>()
    155     _find_jvm_mac()
    156 
--> 157 import javabridge._javabridge as _javabridge
    158 __dead_event = threading.Event()
    159 __kill = [False]

ImportError: No module named 'javabridge._javabridge'

So apparently, it did not work after all? Or have I changed environments when starting ipython?
NB: Based on the last thought, I called
$ python demo_nogui.py
Hello, world!

so it works but I can't use ipython any more?
When interactively using python, I can import javabridge but not use it.

**Comment by LeeKamentsky** [comment]
The import of javabridge in ipython is failing because your home directory is the root of the git repo. Change your directory to something else, like /Users/grabmayr and try again.

I recommended that you use a virtual environment to avoid having to install as superuser. If installing as superuser is not a problem for you, go ahead.

**Comment by Heerpa** [comment]
Awesome, thanks! It is all working now.
No offence about the virtual environment. It seems very handy - just trying to learn..
